INSERT INTO HOBBY VALUES ('3D-udskrivning','https://en.wikipedia.org/wiki/3D_printing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Akrobatik','https://en.wikipedia.org/wiki/Acrobatics','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Skuespil','https://en.wikipedia.org/wiki/Acting','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Amatørradio','https://en.wikipedia.org/wiki/Amateur_radio','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Animation','https://en.wikipedia.org/wiki/Animation','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Aquascaping','https://en.wikipedia.org/wiki/Aquascaping','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Astrologi','https://en.wikipedia.org/wiki/Astrology','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Bagning','https://en.wikipedia.org/wiki/Baking','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Baton snurrer','https://en.wikipedia.org/wiki/Baton_twirling','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Blogging','https://en.wikipedia.org/wiki/Blogging','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Brætspil','https://en.wikipedia.org/wiki/Board_game','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Bogdiskussionsklub','https://en.wikipedia.org/wiki/Book_discussion_club','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Gendannelse af bøger','https://en.wikipedia.org/wiki/Book_restoration','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Bowling','https://en.wikipedia.org/wiki/Bowling','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Brasiliansk jiu-jitsu','https://en.wikipedia.org/wiki/Brazilian_jiu-jitsu','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Brødfremstilling','https://en.wikipedia.org/wiki/Breadmaking','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Bygning','https://en.wikipedia.org/wiki/Building','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Bullet Journal','https://en.wikipedia.org/wiki/Bullet_Journal','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Cabaret','https://en.wikipedia.org/wiki/Cabaret','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Kalligrafi','https://en.wikipedia.org/wiki/Calligraphy','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Lysfremstilling','https://en.wikipedia.org/wiki/Candle_making','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Slikfremstilling','https://en.wikipedia.org/wiki/Candy_making','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Bil','https://en.wikipedia.org/wiki/Car','Generel','Indendørs/Udendørs');
INSERT INTO HOBBY VALUES ('Kortspil','https://en.wikipedia.org/wiki/Card_games','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Cardistry','https://en.wikipedia.org/wiki/Cardistry','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Ostemagning','https://en.wikipedia.org/wiki/Cheesemaking','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Rengøring','https://en.wikipedia.org/wiki/Cleaning','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Tøj','https://en.wikipedia.org/wiki/Clothing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Hjemmelavet kaffe','https://en.wikipedia.org/wiki/Home_roasting_coffee','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Indsamling','https://en.wikipedia.org/wiki/Collecting','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Malebog','https://en.wikipedia.org/wiki/Coloring_book','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Computer programmering','https://en.wikipedia.org/wiki/Computer_programming','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Konfekture','https://en.wikipedia.org/wiki/Confectionery','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Madlavning','https://en.wikipedia.org/wiki/Cooking','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Cosplaying','https://en.wikipedia.org/wiki/Cosplaying','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Kuponering','https://en.wikipedia.org/wiki/Couponing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Håndværk','https://en.wikipedia.org/wiki/Craft','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Kreativ skrivning','https://en.wikipedia.org/wiki/Creative_writing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Hækling','https://en.wikipedia.org/wiki/Crocheting','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Korssting','https://en.wikipedia.org/wiki/Cross-stitch','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Krydsogtværs','https://en.wikipedia.org/wiki/Crossword_puzzles','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Kryptografi','https://en.wikipedia.org/wiki/Cryptography','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Cue sport','https://en.wikipedia.org/wiki/Cue_sports','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Dans','https://en.wikipedia.org/wiki/Dance','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Digital kunst','https://en.wikipedia.org/wiki/Digital_art','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Distro-hopping','https://en.wikipedia.org/wiki/Distro-hopping','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Disc-jockey','https://en.wikipedia.org/wiki/Disc-jockey','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Gør det selv','https://en.wikipedia.org/wiki/Do_it_yourself','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Drama','https://en.wikipedia.org/wiki/Drama','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Tegning','https://en.wikipedia.org/wiki/Drawing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Blandet drik','https://en.wikipedia.org/wiki/Mixed_drink','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Drikker','https://en.wikipedia.org/wiki/Drinking','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Elektroniske spil','https://en.wikipedia.org/wiki/Electronic_games','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Elektronik','https://en.wikipedia.org/wiki/Electronics','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Broderi','https://en.wikipedia.org/wiki/Embroidery','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Eksperimenterer','https://en.wikipedia.org/wiki/Experimenting','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Fantasy sport','https://en.wikipedia.org/wiki/Fantasy_sport','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Mode','https://en.wikipedia.org/wiki/Fashion','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Mode design','https://en.wikipedia.org/wiki/Fashion_design','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Fiskearbejde','https://en.wikipedia.org/wiki/Fishkeeping','Generel',' Observation');
INSERT INTO HOBBY VALUES ('Filmfremstilling','https://en.wikipedia.org/wiki/Filmmaking','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Blomsterbinding','https://en.wikipedia.org/wiki/Flower_arranging','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Fluebinding','https://en.wikipedia.org/wiki/Fly_tying','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Andet sprog erhvervelse','https://en.wikipedia.org/wiki/Second-language_acquisition','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Møbel','https://en.wikipedia.org/wiki/Furniture','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Spil','https://en.wikipedia.org/wiki/Games','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Bordspil','https://en.wikipedia.org/wiki/Tabletop_game','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Rollespil','https://en.wikipedia.org/wiki/Role-playing_game','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Slægtsforskning','https://en.wikipedia.org/wiki/Genealogy','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Honningkagehus','https://en.wikipedia.org/wiki/Gingerbread_house','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Glasblæsning','https://en.wikipedia.org/wiki/Glassblowing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Grafisk design','https://en.wikipedia.org/wiki/Graphic_design','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Gunsmithing','https://en.wikipedia.org/wiki/Gunsmithing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Gymnastik','https://en.wikipedia.org/wiki/Gymnastics','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Hacker','https://en.wikipedia.org/wiki/Hacker','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Herpetokultur','https://en.wikipedia.org/wiki/Herpetoculture','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Hjemmeforbedring','https://en.wikipedia.org/wiki/Home_improvement','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Hjemmebrygning','https://en.wikipedia.org/wiki/Homebrewing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Pleje af husplanter','https://en.wikipedia.org/wiki/Houseplant_care','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Hula bøjning','https://en.wikipedia.org/wiki/Hula_hooping','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Humor','https://en.wikipedia.org/wiki/Humor','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Hydroponics','https://en.wikipedia.org/wiki/Hydroponics','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Skøjteløb','https://en.wikipedia.org/wiki/Ice_skating','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Smykkefremstilling','https://en.wikipedia.org/wiki/Jewelry_making','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Puslespil','https://en.wikipedia.org/wiki/Jigsaw_puzzles','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Dagbog','https://en.wikipedia.org/wiki/Diary','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Jonglere','https://en.wikipedia.org/wiki/Juggling','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Karaoke','https://en.wikipedia.org/wiki/Karaoke','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Karate','https://en.wikipedia.org/wiki/Karate','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Kendama','https://en.wikipedia.org/wiki/Kendama','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Knivfremstilling','https://en.wikipedia.org/wiki/Knife_making','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Strikning','https://en.wikipedia.org/wiki/Knitting','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Knude binder','https://en.wikipedia.org/wiki/Knot_tying','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Kombucha','https://en.wikipedia.org/wiki/Kombucha','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Blonder','https://en.wikipedia.org/wiki/Lace_making','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Lapidary','https://en.wikipedia.org/wiki/Lapidary','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Læder håndværk','https://en.wikipedia.org/wiki/Leather_crafting','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Lego','https://en.wikipedia.org/wiki/Lego','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('musik','https://en.wikipedia.org/wiki/Music','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Podcasts','https://en.wikipedia.org/wiki/Podcasts','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Låseplukning','https://en.wikipedia.org/wiki/Lock_picking','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Bearbejdning','https://en.wikipedia.org/wiki/Machining','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Macrame','https://en.wikipedia.org/wiki/Macrame','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Magi (illusion)','https://en.wikipedia.org/wiki/Magic_(illusion)','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Makeup','https://en.wikipedia.org/wiki/Makeup','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Labyrint','https://en.wikipedia.org/wiki/Maze','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Metalbearbejdning','https://en.wikipedia.org/wiki/Metalworking','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Modelbygning','https://en.wikipedia.org/wiki/Model_building','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Model engineering','https://en.wikipedia.org/wiki/Model_engineering','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Negle kunst','https://en.wikipedia.org/wiki/Nail_art','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Nålepunkt','https://en.wikipedia.org/wiki/Needlepoint','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Origami','https://en.wikipedia.org/wiki/Origami','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Maleri','https://en.wikipedia.org/wiki/Painting','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Håndflade','https://en.wikipedia.org/wiki/Palmistry','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Adoption af kæledyr','https://en.wikipedia.org/wiki/Pet_adoption','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Filateli','https://en.wikipedia.org/wiki/Philately','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Fotografering','https://en.wikipedia.org/wiki/Photography','Generel',' Observation');
INSERT INTO HOBBY VALUES ('Pilates','https://en.wikipedia.org/wiki/Pilates','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Poi (performance)','https://en.wikipedia.org/wiki/Poi_(performance_art)','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Pole Dancing (siden findes ikke)','https://en.wikipedia.org/w/index.php?title=Pole_Dancing&action=edit&redlink=1','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Keramik','https://en.wikipedia.org/wiki/Pottery','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Kraftløftning','https://en.wikipedia.org/wiki/Powerlifting','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Praktiske vittigheder','https://en.wikipedia.org/wiki/Practical_jokes','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Presset blomsterhåndværk','https://en.wikipedia.org/wiki/Pressed_flower_craft','Generel',' Samler hobbyer');
INSERT INTO HOBBY VALUES ('Gåde','https://en.wikipedia.org/wiki/Puzzle','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Quilling','https://en.wikipedia.org/wiki/Quilling','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Quiltning','https://en.wikipedia.org/wiki/Quilting','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Quizzer','https://en.wikipedia.org/wiki/Quizzes','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Radiostyret model','https://en.wikipedia.org/wiki/Radio-controlled_model','Generel',' Samler hobbyer');
INSERT INTO HOBBY VALUES ('Modellering af jernbanetransport','https://en.wikipedia.org/wiki/Rail_transport_modeling','Generel',' Samler hobbyer');
INSERT INTO HOBBY VALUES ('Rapping','https://en.wikipedia.org/wiki/Rapping','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Læsning','https://en.wikipedia.org/wiki/Reading','Generel',' Observation');
INSERT INTO HOBBY VALUES ('Efterbehandling','https://en.wikipedia.org/wiki/Refinishing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Reiki','https://en.wikipedia.org/wiki/Reiki','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Robotkamp','https://en.wikipedia.org/wiki/Robot_combat','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Rubiks terning','https://en.wikipedia.org/wiki/Rubik%27s_Cube','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Scrapbooking','https://en.wikipedia.org/wiki/Scrapbooking','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('SCUBA Dykning','https://en.wikipedia.org/wiki/SCUBA_Diving','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Modellering','https://en.wikipedia.org/wiki/Sculpting','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Syning','https://en.wikipedia.org/wiki/Sewing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Skomageri','https://en.wikipedia.org/wiki/Shoemaking','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Synger','https://en.wikipedia.org/wiki/Singing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Skitse (tegning)','https://en.wikipedia.org/wiki/Sketch_(drawing)','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Sjippetov','https://en.wikipedia.org/wiki/Skipping_rope','Generel','Indendørs/Udendørs');
INSERT INTO HOBBY VALUES ('Slot bil','https://en.wikipedia.org/wiki/Slot_car','Generel',' Samler hobbyer');
INSERT INTO HOBBY VALUES ('Sæbefremstilling','https://en.wikipedia.org/wiki/Soapmaking','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Sociale medier','https://en.wikipedia.org/wiki/Social_media','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Regneark','https://en.wikipedia.org/wiki/Spreadsheets','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Stand-up','https://en.wikipedia.org/wiki/Stand-up_comedy','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Frimærkesamling','https://en.wikipedia.org/wiki/Stamp_collecting','Generel',' Samler hobbyer');
INSERT INTO HOBBY VALUES ('Bordtennis','https://en.wikipedia.org/wiki/Table_tennis','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Tarot','https://en.wikipedia.org/wiki/Tarot','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Taksidermi','https://en.wikipedia.org/wiki/Taxidermy','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Velgørenhedsbutik','https://en.wikipedia.org/wiki/Charity_shop','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Videoredigering','https://en.wikipedia.org/wiki/Video_editing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Udvikling af videospil','https://en.wikipedia.org/wiki/Video_game_development','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Videospil','https://en.wikipedia.org/wiki/Video_gaming','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Videografi','https://en.wikipedia.org/wiki/Videography','Generel','Indendørs/Udendørs');
INSERT INTO HOBBY VALUES ('Virtual reality','https://en.wikipedia.org/wiki/Virtual_reality','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Film','https://en.wikipedia.org/wiki/Movies','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Tv-program','https://en.wikipedia.org/wiki/Television_program','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Voksning','https://en.wikipedia.org/wiki/Waxing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Vævning','https://en.wikipedia.org/wiki/Weaving','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Webtoon','https://en.wikipedia.org/wiki/Webtoon','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Vægt træning','https://en.wikipedia.org/wiki/Weight_training','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Svejsning','https://en.wikipedia.org/wiki/Welding','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Hviskende','https://en.wikipedia.org/wiki/Whittling','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Vinfremstilling','https://en.wikipedia.org/wiki/Winemaking','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Træskæring','https://en.wikipedia.org/wiki/Wood_carving','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Træbearbejdning','https://en.wikipedia.org/wiki/Woodworking','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Ordsøgninger','https://en.wikipedia.org/wiki/Word_searches','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Verdensbygning','https://en.wikipedia.org/wiki/Worldbuilding','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Skrivning','https://en.wikipedia.org/wiki/Writing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Yo-yoing','https://en.wikipedia.org/wiki/Yo-yoing','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Yoga','https://en.wikipedia.org/wiki/Yoga','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Zumba','https://en.wikipedia.org/wiki/Zumba','Generel','Indendørs');
INSERT INTO HOBBY VALUES ('Luftsport','https://en.wikipedia.org/wiki/Air_sports','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Airsoft','https://en.wikipedia.org/wiki/Airsoft','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Amatørgeologi','https://en.wikipedia.org/wiki/Amateur_geology','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Forlystelsespark','https://en.wikipedia.org/wiki/Amusement_park','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Bueskydning','https://en.wikipedia.org/wiki/Archery','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Astronomi','https://en.wikipedia.org/wiki/Astronomy','Generel',' Educational hobbies');
INSERT INTO HOBBY VALUES ('Backpacking (vildmark)','https://en.wikipedia.org/wiki/Backpacking_(wilderness)','Generel',' Observation');
INSERT INTO HOBBY VALUES ('Badminton','https://en.wikipedia.org/wiki/Badminton','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Base jumping','https://en.wikipedia.org/wiki/BASE_jumping','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Baseball','https://en.wikipedia.org/wiki/Baseball','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Basketball','https://en.wikipedia.org/wiki/Basketball','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Biavl','https://en.wikipedia.org/wiki/Beekeeping','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Fuglekiggeri','https://en.wikipedia.org/wiki/Birdwatching','Generel',' Observation');
INSERT INTO HOBBY VALUES ('Smedarbejde','https://en.wikipedia.org/wiki/Blacksmithing','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('BMX','https://en.wikipedia.org/wiki/BMX','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Brætsport','https://en.wikipedia.org/wiki/Board_sports','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Bodybuilding','https://en.wikipedia.org/wiki/Bodybuilding','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Bonsai','https://en.wikipedia.org/wiki/Bonsai','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Sommerfugletur','https://en.wikipedia.org/wiki/Butterfly_watching','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Bus','https://en.wikipedia.org/wiki/Bus','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Camping','https://en.wikipedia.org/wiki/Camping','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Kanosejlads','https://en.wikipedia.org/wiki/Canoeing','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Canyoning','https://en.wikipedia.org/wiki/Canyoning','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Huleforskning','https://en.wikipedia.org/wiki/Caving','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Kompostering','https://en.wikipedia.org/wiki/Composting','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Cykling','https://en.wikipedia.org/wiki/Cycling','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Dowsing','https://en.wikipedia.org/wiki/Dowsing','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Kørsel','https://en.wikipedia.org/wiki/Driving','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Landbrug','https://en.wikipedia.org/wiki/Farming','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Fiskeri','https://en.wikipedia.org/wiki/Fishing','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Flag fodbold','https://en.wikipedia.org/wiki/Flag_football','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Blomst','https://en.wikipedia.org/wiki/Flower','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Luftfart','https://en.wikipedia.org/wiki/Aviation','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Flyvende skive','https://en.wikipedia.org/wiki/Flying_disc','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Foder','https://en.wikipedia.org/wiki/Foraging','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Fossicking','https://en.wikipedia.org/wiki/Fossicking','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Freestyle fodbold','https://en.wikipedia.org/wiki/Freestyle_football','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Havearbejde','https://en.wikipedia.org/wiki/Gardening','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Geocaching','https://en.wikipedia.org/wiki/Geocaching','Generel',' Observation');
INSERT INTO HOBBY VALUES ('Spøgelsesjagt','https://en.wikipedia.org/wiki/Ghost_hunting','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Guldprospektering','https://en.wikipedia.org/wiki/Gold_prospecting','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Graffiti','https://en.wikipedia.org/wiki/Graffiti','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Håndbold','https://en.wikipedia.org/wiki/Handball','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Naturlægemidler','https://en.wikipedia.org/wiki/Herbalism','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Herping','https://en.wikipedia.org/wiki/Herping','Generel',' Observation');
INSERT INTO HOBBY VALUES ('Højeffektiv raket','https://en.wikipedia.org/wiki/High-power_rocketry','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Vandreture','https://en.wikipedia.org/wiki/Hiking','Generel',' Observation');
INSERT INTO HOBBY VALUES ('Hobby hest','https://en.wikipedia.org/wiki/Hobby_horse','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Hobby tunneling','https://en.wikipedia.org/wiki/Hobby_tunneling','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Hooping','https://en.wikipedia.org/wiki/Hooping','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Ridning','https://en.wikipedia.org/wiki/Horseback_riding','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Jagt','https://en.wikipedia.org/wiki/Hunting','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('In-line skating','https://en.wikipedia.org/wiki/Inline_skating','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Løbe','https://en.wikipedia.org/wiki/Jogging','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Ro kajak','https://en.wikipedia.org/wiki/Kayaking','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Glente','https://en.wikipedia.org/wiki/Kite','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Kitesurfing','https://en.wikipedia.org/wiki/Kitesurfing','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Lacrosse','https://en.wikipedia.org/wiki/Lacrosse','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('LARPing','https://en.wikipedia.org/wiki/LARPing','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Letterboxing (hobby)','https://en.wikipedia.org/wiki/Letterboxing_(hobby)','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Longboarding','https://en.wikipedia.org/wiki/Longboarding','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Kampsport','https://en.wikipedia.org/wiki/Martial_arts','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Metaldetektor','https://en.wikipedia.org/wiki/Metal_detector','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Meteorologi','https://en.wikipedia.org/wiki/Meteorology','Generel',' Observation');
INSERT INTO HOBBY VALUES ('Motorsport','https://en.wikipedia.org/wiki/Motor_sports','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Mountainbiking','https://en.wikipedia.org/wiki/Mountain_biking','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Bjergbestigning','https://en.wikipedia.org/wiki/Mountaineering','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Museum','https://en.wikipedia.org/wiki/Museum','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Svampejagt','https://en.wikipedia.org/wiki/Mushroom_hunting','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Mykologi','https://en.wikipedia.org/wiki/Mycology','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Netball','https://en.wikipedia.org/wiki/Netball','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Nordisk skøjteløb','https://en.wikipedia.org/wiki/Nordic_skating','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Orientering','https://en.wikipedia.org/wiki/Orienteering','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Paintball','https://en.wikipedia.org/wiki/Paintball','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Parkour','https://en.wikipedia.org/wiki/Parkour','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Podcast','https://en.wikipedia.org/wiki/Podcast','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Polo','https://en.wikipedia.org/wiki/Polo','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Offentlig transport','https://en.wikipedia.org/wiki/Public_transport','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Rafting','https://en.wikipedia.org/wiki/Rafting','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Jernbane','https://en.wikipedia.org/wiki/Railway','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Rappellering','https://en.wikipedia.org/wiki/Rappelling','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Road Cykling','https://en.wikipedia.org/wiki/Road_Cycling','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Rulleskøjteløb','https://en.wikipedia.org/wiki/Roller_skating','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Rugby fodbold','https://en.wikipedia.org/wiki/Rugby_football','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Løb','https://en.wikipedia.org/wiki/Running','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Sejler','https://en.wikipedia.org/wiki/Sailing','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Sand kunst og leg','https://en.wikipedia.org/wiki/Sand_art_and_play','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Spejder','https://en.wikipedia.org/wiki/Scouting','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Dykning','https://en.wikipedia.org/wiki/Scuba_diving','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Sculling','https://en.wikipedia.org/wiki/Sculling','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Roning (sport)','https://en.wikipedia.org/wiki/Rowing_(sport)','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Optagelse','https://en.wikipedia.org/wiki/Shooting','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Handle ind','https://en.wikipedia.org/wiki/Shopping','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Shuffleboard','https://en.wikipedia.org/wiki/Shuffleboard','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Skateboarding','https://en.wikipedia.org/wiki/Skateboarding','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Stå på ski','https://en.wikipedia.org/wiki/Skiing','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Skimboarding','https://en.wikipedia.org/wiki/Skimboarding','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Faldskærmsudspring','https://en.wikipedia.org/wiki/Skydiving','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Slacklining','https://en.wikipedia.org/wiki/Slacklining','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Snowboarding','https://en.wikipedia.org/wiki/Snowboarding','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Snescooterkørsel','https://en.wikipedia.org/wiki/Snowmobiling','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Snesko','https://en.wikipedia.org/wiki/Snowshoeing','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Fodbold','https://en.wikipedia.org/wiki/Soccer','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Sten springer over','https://en.wikipedia.org/wiki/Stone_skipping','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Solbadning','https://en.wikipedia.org/wiki/Sun_bathing','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Surfing','https://en.wikipedia.org/wiki/Surfing','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Overlevelse','https://en.wikipedia.org/wiki/Survivalism','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Menneskelig svømning','https://en.wikipedia.org/wiki/Human_swimming','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Taekwondo','https://en.wikipedia.org/wiki/Taekwondo','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Tai Chi','https://en.wikipedia.org/wiki/Tai_chi','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Tennis','https://en.wikipedia.org/wiki/Tennis','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Topiary','https://en.wikipedia.org/wiki/Topiary','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Turisme','https://en.wikipedia.org/wiki/Tourism','Generel',' Konkurrence');
INSERT INTO HOBBY VALUES ('Gennem vandring','https://en.wikipedia.org/wiki/Thru-hiking','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Messe','https://en.wikipedia.org/wiki/Trade_fair','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Rejse','https://en.wikipedia.org/wiki/Travel','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Byudforskning','https://en.wikipedia.org/wiki/Urban_exploration','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Ferie','https://en.wikipedia.org/wiki/Vacation','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Vegetabilsk landbrug','https://en.wikipedia.org/wiki/Vegetable_farming','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Restaurering af køretøjet','https://en.wikipedia.org/wiki/Vehicle_restoration','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Gå','https://en.wikipedia.org/wiki/Walking','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Vandsport','https://en.wikipedia.org/wiki/Water_sports','Generel','Udendørs');
INSERT INTO HOBBY VALUES ('Biologi','https://en.wikipedia.org/wiki/Biology','Educational hobbies','---');
INSERT INTO HOBBY VALUES ('Kemi','https://en.wikipedia.org/wiki/Chemistry','Educational hobbies','---');
INSERT INTO HOBBY VALUES ('Elektrokemi','https://en.wikipedia.org/wiki/Electrochemistry','Educational hobbies','---');
INSERT INTO HOBBY VALUES ('Geografi','https://en.wikipedia.org/wiki/Geography','Educational hobbies','---');
INSERT INTO HOBBY VALUES ('Historie','https://en.wikipedia.org/wiki/History','Educational hobbies','---');
INSERT INTO HOBBY VALUES ('Matematik','https://en.wikipedia.org/wiki/Mathematics','Educational hobbies','---');
INSERT INTO HOBBY VALUES ('Psykologi','https://en.wikipedia.org/wiki/Psychology','Educational hobbies','---');
INSERT INTO HOBBY VALUES ('Fysik','https://en.wikipedia.org/wiki/Physics','Educational hobbies','---');
INSERT INTO HOBBY VALUES ('Jernbanetransport','https://en.wikipedia.org/wiki/Rail_transport','Educational hobbies','---');
INSERT INTO HOBBY VALUES ('Videnskab og teknologi studier','https://en.wikipedia.org/wiki/Science_and_technology_studies','Educational hobbies','---');
INSERT INTO HOBBY VALUES ('Sociale Studier','https://en.wikipedia.org/wiki/Social_studies','Educational hobbies','---');
INSERT INTO HOBBY VALUES ('Sportsvidenskab','https://en.wikipedia.org/wiki/Sports_science','Educational hobbies','---');
INSERT INTO HOBBY VALUES ('Action figur','https://en.wikipedia.org/wiki/Action_figure','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Antikviteter','https://en.wikipedia.org/wiki/Antiquing','Samler hobbyer','Indendørs/Udendørs');
INSERT INTO HOBBY VALUES ('Ant-holder','https://en.wikipedia.org/wiki/Ant-keeping','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Kunstindsamling','https://en.wikipedia.org/wiki/Art_collecting','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Bogindsamling','https://en.wikipedia.org/wiki/Book_collecting','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Knapopsamling','https://en.wikipedia.org/wiki/Button_collecting','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Bytte kort','https://en.wikipedia.org/wiki/Trading_cards','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Møntindsamling','https://en.wikipedia.org/wiki/Coin_collecting','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Tegneserieindsamling','https://en.wikipedia.org/wiki/Comic_book_collecting','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Deltiologi','https://en.wikipedia.org/wiki/Deltiology','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Die-cast legetøj','https://en.wikipedia.org/wiki/Die-cast_toy','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Digital hamstring','https://en.wikipedia.org/wiki/Digital_hoarding','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Dukker','https://en.wikipedia.org/wiki/Dolls','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Elementindsamling','https://en.wikipedia.org/wiki/Element_collecting','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Flygtig','https://en.wikipedia.org/wiki/Ephemera','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Telefonkort','https://en.wikipedia.org/wiki/Telephone_card','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Knivopsamling','https://en.wikipedia.org/wiki/Knife_collecting','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Lotologi','https://en.wikipedia.org/wiki/Lotology','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Film memorabilia','https://en.wikipedia.org/wiki/Film_memorabilia','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Fingeraftryk','https://en.wikipedia.org/wiki/Fingerprint','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Parfume','https://en.wikipedia.org/wiki/Perfume','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Phillumeny','https://en.wikipedia.org/wiki/Phillumeny','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Pladesamling','https://en.wikipedia.org/wiki/Record_collecting','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Rock tumbling','https://en.wikipedia.org/wiki/Rock_tumbling','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Patch indsamling','https://en.wikipedia.org/wiki/Patch_collecting','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Sko','https://en.wikipedia.org/wiki/Shoes','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Sportsmemorabilia','https://en.wikipedia.org/wiki/Sports_memorabilia','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Tøjdyr','https://en.wikipedia.org/wiki/Stuffed_toy','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Te pose','https://en.wikipedia.org/wiki/Tea_bag','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Billet (adgang)','https://en.wikipedia.org/wiki/Ticket_(admission)','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Legetøj','https://en.wikipedia.org/wiki/Toys','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Transitkort','https://en.wikipedia.org/wiki/Transit_map','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Samling af videospil','https://en.wikipedia.org/wiki/Video_game_collecting','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Vintage biler','https://en.wikipedia.org/wiki/Vintage_cars','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Vintage tøj','https://en.wikipedia.org/wiki/Vintage_clothing','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Vinylplader','https://en.wikipedia.org/wiki/Vinyl_Records','Samler hobbyer','Indendørs');
INSERT INTO HOBBY VALUES ('Auto audiophilia','https://en.wikipedia.org/wiki/Auto_audiophilia','Samler hobbyer','Udendørs');
INSERT INTO HOBBY VALUES ('Fossil jagt','https://en.wikipedia.org/wiki/Fossil_hunting','Samler hobbyer','Udendørs');
INSERT INTO HOBBY VALUES ('Insektindsamling','https://en.wikipedia.org/wiki/Insect_collecting','Samler hobbyer','Udendørs');
INSERT INTO HOBBY VALUES ('Magnetfiskeri','https://en.wikipedia.org/wiki/Magnet_fishing','Samler hobbyer','Udendørs');
INSERT INTO HOBBY VALUES ('Metaldetektering','https://en.wikipedia.org/wiki/Metal_detecting','Samler hobbyer','Udendørs');
INSERT INTO HOBBY VALUES ('Mineralindsamling','https://en.wikipedia.org/wiki/Mineral_collecting','Samler hobbyer','Udendørs');
INSERT INTO HOBBY VALUES ('Stenbalancering','https://en.wikipedia.org/wiki/Rock_balancing','Samler hobbyer','Udendørs');
INSERT INTO HOBBY VALUES ('Havglas','https://en.wikipedia.org/wiki/Sea_glass','Samler hobbyer','Udendørs');
INSERT INTO HOBBY VALUES ('Muslingeskal','https://en.wikipedia.org/wiki/Seashell','Samler hobbyer','Udendørs');
INSERT INTO HOBBY VALUES ('Stenopsamling','https://en.wikipedia.org/wiki/Stone_collecting','Samler hobbyer','Udendørs');
INSERT INTO HOBBY VALUES ('Dyrepleje','https://en.wikipedia.org/wiki/Animal_fancy','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Øksekast','https://en.wikipedia.org/wiki/Axe_throwing','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Backgammon','https://en.wikipedia.org/wiki/Backgammon','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Skønhedskonkurrence','https://en.wikipedia.org/wiki/Beauty_pageant','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Boksning','https://en.wikipedia.org/wiki/Boxing','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Kontraktsbro','https://en.wikipedia.org/wiki/Contract_Bridge','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Kladder','https://en.wikipedia.org/wiki/Draughts','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Cheerleading','https://en.wikipedia.org/wiki/Cheerleading','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Skak','https://en.wikipedia.org/wiki/Chess','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Farvebeskyttelse (flag spinding)','https://en.wikipedia.org/wiki/Color_guard_(flag_spinning)','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Cribbage','https://en.wikipedia.org/wiki/Cribbage','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Curling','https://en.wikipedia.org/wiki/Curling','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Konkurrencedygtig dans','https://en.wikipedia.org/wiki/Competitive_dance','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Dart','https://en.wikipedia.org/wiki/Darts','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Debat','https://en.wikipedia.org/wiki/Debate','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Dominoer','https://en.wikipedia.org/wiki/Dominoes','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Konkurrencedygtig spisning','https://en.wikipedia.org/wiki/Competitive_eating','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Esports','https://en.wikipedia.org/wiki/Esports','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Hegn','https://en.wikipedia.org/wiki/Fencing','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Gå (spil)','https://en.wikipedia.org/wiki/Go_(game)','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Ishockey','https://en.wikipedia.org/wiki/Ice_hockey','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Judo','https://en.wikipedia.org/wiki/Judo','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Jujitsu','https://en.wikipedia.org/wiki/Jujitsu','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Kabaddi','https://en.wikipedia.org/wiki/Kabaddi','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Ordspil','https://en.wikipedia.org/wiki/Word_games','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Lasermærke','https://en.wikipedia.org/wiki/Laser_tag','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Mahjong','https://en.wikipedia.org/wiki/Mahjong','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Kugler','https://en.wikipedia.org/wiki/Marbles','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Model FN','https://en.wikipedia.org/wiki/Model_United_Nations','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Poker','https://en.wikipedia.org/wiki/Poker','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Pool (cue sports)','https://en.wikipedia.org/wiki/Pool_(cue_sports)','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Shogi','https://en.wikipedia.org/wiki/Shogi','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Slot bilspil','https://en.wikipedia.org/wiki/Slot_car_racing','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Hurtigkubning','https://en.wikipedia.org/wiki/Speedcubing','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Sport stabling','https://en.wikipedia.org/wiki/Sport_stacking','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Bordfodbold','https://en.wikipedia.org/wiki/Table_football','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Volleyball','https://en.wikipedia.org/wiki/Volleyball','Konkurrence','Indendørs/Udendørs');
INSERT INTO HOBBY VALUES ('Brydning','https://en.wikipedia.org/wiki/Wrestling','Konkurrence','Indendørs');
INSERT INTO HOBBY VALUES ('Association fodbold','https://en.wikipedia.org/wiki/Association_football','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Australsk spiller fodbold','https://en.wikipedia.org/wiki/Australian_rules_football','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Bilsport','https://en.wikipedia.org/wiki/Auto_racing','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Beach Volleyball','https://en.wikipedia.org/wiki/Beach_volleyball','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Breakdancing','https://en.wikipedia.org/wiki/Breakdancing','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Klatring','https://en.wikipedia.org/wiki/Climbing','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Cricket','https://en.wikipedia.org/wiki/Cricket','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Croquet','https://en.wikipedia.org/wiki/Croquet','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Disc golf','https://en.wikipedia.org/wiki/Disc_golf','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Hundesport','https://en.wikipedia.org/wiki/Dog_sport','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Udstillingsøvelse','https://en.wikipedia.org/wiki/Exhibition_drill','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Field hockey','https://en.wikipedia.org/wiki/Field_hockey','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Kunstskøjteløb','https://en.wikipedia.org/wiki/Figure_skating','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Fodtaske','https://en.wikipedia.org/wiki/Footbag','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Frisbee','https://en.wikipedia.org/wiki/Frisbee','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Golf','https://en.wikipedia.org/wiki/Golf','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Hestesko','https://en.wikipedia.org/wiki/Horseshoes','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Isbåd','https://en.wikipedia.org/wiki/Iceboat','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Jukskei','https://en.wikipedia.org/wiki/Jukskei','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Kart racing','https://en.wikipedia.org/wiki/Kart_racing','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Knivkastning','https://en.wikipedia.org/wiki/Knife_throwing','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Langdistanceløb','https://en.wikipedia.org/wiki/Long-distance_running','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Marcherende band','https://en.wikipedia.org/wiki/Marching_band','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Modelfly','https://en.wikipedia.org/wiki/Model_aircraft','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Pickleball','https://en.wikipedia.org/wiki/Pickleball','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Quidditch (sport)','https://en.wikipedia.org/wiki/Quidditch_(sport)','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Race gåtur','https://en.wikipedia.org/wiki/Race_walking','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Racquetball','https://en.wikipedia.org/wiki/Racquetball','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Radiostyret bil','https://en.wikipedia.org/wiki/Radio-controlled_car','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Roller derby','https://en.wikipedia.org/wiki/Roller_derby','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Rugby liga','https://en.wikipedia.org/wiki/Rugby_league','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Roning','https://en.wikipedia.org/wiki/Rowing','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Skydesport','https://en.wikipedia.org/wiki/Shooting_sport','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Slædehundevæddeløb','https://en.wikipedia.org/wiki/Sled_dog_racing','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Softball','https://en.wikipedia.org/wiki/Softball','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Hurtigløb på skøjter','https://en.wikipedia.org/wiki/Speed_skating','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Squash (sport)','https://en.wikipedia.org/wiki/Squash_(sport)','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Tennispolo','https://en.wikipedia.org/wiki/Tennis_polo','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Fastgør bil','https://en.wikipedia.org/wiki/Tether_car','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Tour skøjteløb','https://en.wikipedia.org/wiki/Tour_skating','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Trapshooting','https://en.wikipedia.org/wiki/Trapshooting','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Triatlon','https://en.wikipedia.org/wiki/Triathlon','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Ultimate (sport)','https://en.wikipedia.org/wiki/Ultimate_(sport)','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Vandpolo','https://en.wikipedia.org/wiki/Water_polo','Konkurrence','Udendørs');
INSERT INTO HOBBY VALUES ('Læring','https://en.wikipedia.org/wiki/Learning','Observation','Indendørs');
INSERT INTO HOBBY VALUES ('Meditation','https://en.wikipedia.org/wiki/Meditation','Observation','Indendørs');
INSERT INTO HOBBY VALUES ('Mikroskopi','https://en.wikipedia.org/wiki/Microscopy','Observation','Indendørs');
INSERT INTO HOBBY VALUES ('Forskning','https://en.wikipedia.org/wiki/Research','Observation','Indendørs');
INSERT INTO HOBBY VALUES ('Kortbølgelytning','https://en.wikipedia.org/wiki/Shortwave_listening','Observation','Indendørs');
INSERT INTO HOBBY VALUES ('Audiofil','https://en.wikipedia.org/wiki/Audiophile','Observation','Indendørs');
INSERT INTO HOBBY VALUES ('Flyspotting','https://en.wikipedia.org/wiki/Aircraft_spotting','Observation','Udendørs');
INSERT INTO HOBBY VALUES ('Amatør astronomi','https://en.wikipedia.org/wiki/Amateur_astronomy','Observation','Udendørs');
INSERT INTO HOBBY VALUES ('Bus spotting','https://en.wikipedia.org/wiki/Bus_spotting','Observation','Udendørs');
INSERT INTO HOBBY VALUES ('Gongoozler','https://en.wikipedia.org/wiki/Gongoozler','Observation','Udendørs');
INSERT INTO HOBBY VALUES ('Satellitovervågning','https://en.wikipedia.org/wiki/Satellite_watching','Observation','Udendørs');
INSERT INTO HOBBY VALUES ('Trainspotting (hobby)','https://en.wikipedia.org/wiki/Trainspotting_(hobby)','Observation','Udendørs');
INSERT INTO HOBBY VALUES ('Hvalsafari','https://en.wikipedia.org/wiki/Whale_watching','Observation','Udendørs');
